spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          predicates:
            - name: Path
              args:
                regexp: /user-service/**
          uri: lb://user-service

        - id: file-service
          predicates:
            - name: Path
              args:
                regexp: /file-service/**
          uri: lb://file-service

        - id: order-service
          predicates:
            - name: Path
              args:
                regexp: /order-service/**
          uri: lb://order-service

        - id: medical-service
          predicates:
            - name: Path
              args:
                regexp: /medical-service/**
          uri: lb://medical-service

        - id: centre-service
          predicates:
            - name: Path
              args:
                regexp: /centre-service/**
          uri: lb://centre-service
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

    #todo: http://localhost:9999/user-service/user/get/1