spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          predicates:
            - name: Path
              args:
                regexp: /user-service/**
          uri: lb://user-service

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

    #todo: http://localhost:9999/user-service/user/get